#+title: (Abstract) Conceptual Abstraction and Analogy in Natural and Artificial Intelligence
#+roam_alias: caanai20

* Questions and Topics
      - What are potential AI applications in which humanlike concept formation, abstraction, and analogy could improve performance and make systems more robust?
    - What is known in psychology and neuroscience about the mechanisms by which humans (and non-human animals) develop and use concepts, form abstractions, and make analogies?  How can such mechanisms inspire AI research?
    - Can gradient-descent-based systems learn to produce analogical reasoning on novel problems? What can the state-of-the-art in inductive program synthesis teach us about abstraction and reasoning?
     - How can abstraction and analogy-making abilities in AI systems be assessed?  What can we do to ensure that performance on a test will guarantee generalization?
    - Can we discover general computational mechanisms for abstraction and analogy by focusing on idealized microdomains, or could the real challenges lie in interfacing analogical mechanisms with a vast array of commonsense knowledge?
    - If we want machines to creatively invent wholly new theories from data, like scientists do, what roles would abstraction, analogy, and strong generalization play?

* Abstract

  I present a method for inferring formerly represented pathway abstractions from sets of concrete pathways using an algorithm called Least Subsuming Subgraph (LeSS). A pathway abstraction (PA) is a schema for a set of pathways where constituent entities or activities are either left out or left unspecified. A PA may depict a submodule or subgraph in common among its subsumed concrete pathways (SCPs). Several PAs can be organized hierarchically, such as in the Gene Ontology Biological Process (GO-BP) ontology, but formal representations of these pathways depicting the structure and organization of entities and activities do not. PAs allow for modularization of known pathways, such as those in Reactome. Abstraction and modularization can assist in the transfer of knowledge from well understood pathways to new and less well understood pathways. Concrete pathway representations are often incomplete, and finding a good PA can facilitate hypothesis generation by making clear which entities or relationships need to be added, removed, or specified. In addition, pathway enrichment methods may not be able to map data to available target pathways because they either do not take into account causal directionality or require precise mappings to specific entities or activities. PAs can capture the underlying mechanism and allow for abstract matching of constituents. This method is evaluated by inferring PAs from Reactome and reclassifying the SCPs. A good PA will have lost only so much information from its SCPs as to be able to subsume all of them. The success of optimizing the PA information loss will be reflected on the recall and precision of the classification. A good PA will achieve high recall by losing information, thus subsuming more pathways, while it will achieve high precision by retaining information, thus subsuming only those pathways which actually are SCPs.
